#ifndef FSMENUM_H
#define FSMENUM_H

enum StateEnum {
    STATE_UNKNOWN = 0,
    STATE_INIT,
    STATE_GET_FILENAME,
    STATE_GET_OPTION,
    STATE_LAST_MODIFY,
    STATE_CREATED,
    STATE_MAX_SIZE,
    STATE_MIN_SIZE,
    STATE_SIZE,
    STATE_EXT,
    STATE_TYPE,
    STATE_DATE_SPEC,
    STATE_DATE_SPEC_BETWEEN,
    STATE_DATE_SPEC_SINCE_LAST,
    STATE_SIZE_SPEC,
    STATE_SIZE_SPEC_BETWEEN,
    STATE_EX_LIST_SPEC,
    STATE_EX_LIST_SPEC_OR,
    STATE_TYPE_LIST_SPEC,
    STATE_TYPE_LIST_SPEC_OR,
    FINISHED,
    ERROR,
};

#endif //FSMENUM_H
